services:
  miab:
    image: hardware/mailinabox:latest
    container_name: miab
    hostname: ${PRIMARY_HOSTNAME}
    domainname: ${DOMAIN_NAME}
    restart: unless-stopped
    ports:
      # SMTP
      - "25:25"
      - "587:587"
      # IMAP/POP
      - "993:993"
      - "995:995"
      # HTTP/HTTPS
      - "80:80"
      - "443:443"
    volumes:
      - miab_data:/home
      - /etc/localtime:/etc/localtime:ro
    environment:
      - PRIMARY_HOSTNAME=${PRIMARY_HOSTNAME}
      - STORAGE_ROOT=${STORAGE_ROOT}
      - STORAGE_USER=${STORAGE_USER}
      - ADMIN_EMAIL=${ADMIN_EMAIL}
    env_file:
      - .env

volumes:
  miab_data: